name: Deploy API Libreria

on:
  push:
    branches:
      - main  # Se dispara cuando subes cambios a la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore SolucionBiblioteca.sln # Nombre según tu README

    - name: Build
      run: dotnet build SolucionBiblioteca.sln --configuration Release --no-restore

    - name: Publish API
      # Apuntamos a la carpeta Presentation/API según tu estructura
      run: dotnet publish src/Presentation/API/API.csproj -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-libreria-api-prod' # El nombre que le pusiste a tu App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish